.TH "ArmController.Robot_Arm_Module" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.Robot_Arm_Module \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRobotArmModule\fP"
.br
.RI "\fIThis class contains the logic used to control the robot arm with the use of data which is provided by the CyberGlove Module and the Kinect Module\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
