.TH "ArmController.Integration" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.Integration \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBusNode\fP"
.br
.RI "\fIThis enumeration stores known data points which may be queried using the virtual bus\&. \fP"
.ti -1c
.RI "class \fBModule\fP"
.br
.RI "\fIAn abstract interface for each of the modules\&. \fP"
.ti -1c
.RI "class \fBVirtualBus\fP"
.br
.RI "\fIThe virtual bus implements a publish / subscribe architecture to facilitate extensible communication between modules\&. Each module is responsible for subscribing to any relevant nodes, listening for any value-changed events, and publishing any results they may have\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
