.TH "ArmController.Kinect_Module" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.Kinect_Module \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOrientation\fP"
.br
.RI "\fIA simple structure used to describe the orientation of an object in 3d space\&. \fP"
.ti -1c
.RI "class \fBPositionalTracker\fP"
.br
.RI "\fIThis module uses the Kinect to track the position and orientation of the major sections of the user's upper torso\&. \fP"
.ti -1c
.RI "class \fBPositionFeedback\fP"
.br
.RI "\fIThis module is used for debugging purposes\&. It listens for the orientations of the user's right arm on the virtual bus and displays them on screen\&. \fP"
.ti -1c
.RI "class \fBSkeletonRenderer\fP"
.br
.RI "\fIThis class provides us with a means to render a skeleton on a screen\&. This is based on the example provided by the Kinect SDK\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
