.TH "ArmController.Kinect_Module.Orientation" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.Kinect_Module.Orientation \- 
.PP
A simple structure used to describe the orientation of an object in 3d space\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrientation\fP (float roll, float pitch, float yaw)"
.br
.RI "\fIConstruct a new orientation descriptor\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBRoll\fP\fC [get, set]\fP"
.br
.RI "\fIThe roll of the orientation\&. \fP"
.ti -1c
.RI "float \fBPitch\fP\fC [get, set]\fP"
.br
.RI "\fIThe pitch of the orientation\&. \fP"
.ti -1c
.RI "float \fBYaw\fP\fC [get, set]\fP"
.br
.RI "\fIThe yaw of the orientation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A simple structure used to describe the orientation of an object in 3d space\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArmController\&.Kinect_Module\&.Orientation\&.Orientation (floatroll, floatpitch, floatyaw)"

.PP
Construct a new orientation descriptor\&. \fBParameters:\fP
.RS 4
\fIroll\fP The roll of the orientation\&.
.br
\fIpitch\fP The pitch of the orientation\&.
.br
\fIyaw\fP The yaw of the orientation\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "float ArmController\&.Kinect_Module\&.Orientation\&.Pitch\fC [get]\fP, \fC [set]\fP"

.PP
The pitch of the orientation\&. 
.SS "float ArmController\&.Kinect_Module\&.Orientation\&.Roll\fC [get]\fP, \fC [set]\fP"

.PP
The roll of the orientation\&. 
.SS "float ArmController\&.Kinect_Module\&.Orientation\&.Yaw\fC [get]\fP, \fC [set]\fP"

.PP
The yaw of the orientation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
