.TH "ArmController" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBCyberGloveLibrary\fP"
.br
.ti -1c
.RI "package \fBIntegration\fP"
.br
.ti -1c
.RI "package \fBKinect_Module\fP"
.br
.ti -1c
.RI "package \fBRobot_Arm_Module\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "\fIInteraction logic for App\&.xaml \fP"
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fIInteraction logic for MainWindow\&.xaml \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
