.TH "ArmController.App" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.App \- 
.PP
Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
