.TH "ArmController.CyberGloveLibrary" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController.CyberGloveLibrary \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGloveModule\fP"
.br
.RI "\fIA simple class to constantly read data from a CyberGlove\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Robot Arm Controller from the source code\&.
