.TH "ArmController Directory Reference" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCyberGlove Module\fP"
.br
.ti -1c
.RI "directory \fBIntegration\fP"
.br
.ti -1c
.RI "directory \fBKinect Module\fP"
.br
.ti -1c
.RI "directory \fBRobot Arm Module\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.xaml\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainWindow\&.xaml\&.cs\fP"
.br
.in -1c
