.TH "ArmController/Kinect Module Directory Reference" 3 "Fri Dec 14 2012" "Version 0.5" "Robot Arm Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArmController/Kinect Module Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOrientation\&.cs\fP"
.br
.ti -1c
.RI "file \fBPositionalTracker\&.cs\fP"
.br
.ti -1c
.RI "file \fBPositionFeedback\&.cs\fP"
.br
.ti -1c
.RI "file \fBSkeletonRenderer\&.cs\fP"
.br
.in -1c
